### PR TITLE
Hide profile.cov

### PR DESCRIPTION
**Pull request by ordovicia**

### CODE REVIEW

**Comment by dtaniwaki** [comment]
Those files are not only for CI. You need it when you line and get coverage in your machine. And golangci.yaml is a configuration file while profile.cov is a generated file which is ignored in git. I don’t think putting them in .ci directory makes sense.
At least, golangci.yaml should be placed in the root directory or maybe in a config directory.

**Comment by ordovicia** [comment]
> Those files are not only for CI. You need it when you line and get coverage in your machine. And golangci.yaml is a configuration file while profile.cov is a generated file which is ignored in git. I don’t think putting them in .ci directory makes sense.

Right, these files are also used locally by users. I put them in `.ci` directory because I thought they are used in CI in most cases, and users touch through `make`, not directly.
I agree putting `profile.cov` in `.ci` directory is weird, however. How about renaming it to `.profile.cov` (leading dot) so it would be hidden? I want not to see this file in the root directly if possible, even though Git ignores.

> At least, golangci.yaml should be placed in the root directory or maybe in a config directory.

Is it? I confirmed that the config file may be in `.ci` directory as long as the location is specified in the `--config` option.

**Comment by dtaniwaki** [comment]
> > At least, golangci.yaml should be placed in the root directory or maybe in a config directory.
> Is it? I confirmed that the config file may be in .ci directory as long as the location is specified in the --config option.

I mean `.ci` is a hidden directory but the configuration of lint is not something we should hidden.

**Comment by dtaniwaki** [comment]
I'm ok with `.profile.cov`, but if you don't want to see that kind of intermediate file, how about just using a temporary file of `mktemp`?

**Comment by ordovicia** [comment]
> I'm ok with `.profile.cov`, but if you don't want to see that kind of intermediate file, how about just using a temporary file of `mktemp`?

`profile.cov` must be stored persistently since it’s shared with `goveralls`.

> I mean `.ci` is a hidden directory but the configuration of lint is not something we should hide.

I’m not sure which is better, keeping config files visible or hiding them. I understand your point. OTOH `.travis.yml`, `.gitignore` and other config files (ones outside of this repo) are hidden. My opinion about `golangci.yaml` is not so strong, so I’m fine with leaving this file as is.

**Comment by dtaniwaki** [comment]
`mktemp` just creates a temporary file and the generated file is not removed unless you manually delete it. I'm not sure if `after_success` is executed in the same container.

Ok, then how about just leaving `golangci.yaml` as is and rename only `profile.cov` to `.profile.cov`?

**Comment by ordovicia** [comment]
> `mktemp` just creates a temporary file and the generated file is not removed unless you manually delete it. I'm not sure if `after_success` is executed in the same container.

Ah, I misunderstood. Thank you.

> Ok, then how about just leaving `golangci.yaml` as is if there's no reasonable reason, and rename only `profile.cov` to `.profile.cov`?

That's good. I have force-pushed the new change.

**Pull request merged**
